[package]
name = "chat-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { features = ["full"] }
futures = "0.3.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "0.8.2"